const courses=[
{id:"beginner",icon:"🌱",title:"دوره مقدماتی",level:"شروع از صفر",desc:"آشنایی کاربردی با مفاهیم، ابزارها و اصول استفاده از هوش مصنوعی.",about:"برای هنرجویانی که می‌خواهند بدون پیش‌نیاز، AI را درست و پروژه‌محور یاد بگیرند.",sessions:10,duration:"۱۰ جلسه × ۹۰ دقیقه",skills:["شناخت مفاهیم پایه AI","کار با ابزارهای کاربردی","مهندسی پرامپت مقدماتی","ساخت خروجی قابل استفاده"],lessons:["آشنایی با هوش مصنوعی و کاربردهای آن","شناخت ابزارهای تولید متن و تصویر","اصول پرامپت‌نویسی","ساخت پرامپت دقیق و قابل تکرار","کار با ابزارهای تصویری AI","تولید و اصلاح محتوای متنی","ترکیب چند ابزار هوش مصنوعی","حل مسئله با AI","پروژه عملی دوره","ارائه و ارزیابی پروژه"]},
{id:"advanced",icon:"⚡",title:"دوره پیشرفته",level:"سطح پیشرفته",desc:"توسعه مهارت‌های پیشرفته، Workflow و تولید خروجی حرفه‌ای با AI.",about:"برای هنرجویانی که مبانی را می‌دانند و می‌خواهند از کاربر AI به سازنده خروجی حرفه‌ای تبدیل شوند.",sessions:10,duration:"۱۰ جلسه × ۹۰ دقیقه",skills:["پرامپت‌نویسی پیشرفته","طراحی Workflow","ترکیب ابزارهای AI","ساخت خروجی حرفه‌ای"],lessons:["بازطراحی پرامپت‌های ضعیف","پرامپت‌های چندمرحله‌ای","Workflow با چند ابزار","تولید محتوای حرفه‌ای","تولید تصویر و کنترل خروجی","تحلیل و بهبود خروجی AI","ساخت دستیار و فرایند کاری","حل پروژه واقعی","پروژه نهایی","ارائه حرفه‌ای پروژه"]},
{id:"pro",icon:"👑",title:"دوره حرفه‌ای",level:"تخصصی",desc:"ساخت پروژه‌های واقعی و تبدیل مهارت AI به محصول دیجیتال.",about:"مسیر تخصصی برای طراحی، ساخت و ارائه پروژه‌های واقعی با کمک هوش مصنوعی.",sessions:10,duration:"۱۰ جلسه × ۹۰ دقیقه",skills:["طراحی پروژه AI","ساخت محصول دیجیتال","اتوماسیون و Workflow","ارائه و نمونه‌کار"],lessons:["انتخاب ایده و تعریف مسئله","طراحی تجربه کاربر","معماری محصول با AI","ساخت نمونه اولیه","اتصال ابزارها و Workflow","تولید محتوای محصول","تست و رفع ایراد","بهینه‌سازی تجربه کاربری","آماده‌سازی ارائه","پروژه نهایی و ارائه"]},
{id:"income",icon:"💰",title:"کسب درآمد با AI",level:"مهارت درآمدی",desc:"شناخت مسیرهای عملی برای تبدیل مهارت AI به نمونه‌کار و فرصت درآمدی.",about:"تمرکز بر مهارت‌های قابل فروش، ساخت نمونه‌کار و ارائه حرفه‌ای خدمات با AI.",sessions:10,duration:"۱۰ جلسه × ۹۰ دقیقه",skills:["ایده‌پردازی درآمدی","ساخت نمونه‌کار","ارائه خدمات با AI","برندسازی و مذاکره"],lessons:["شناخت مهارت‌های قابل فروش","انتخاب حوزه تخصصی","طراحی خدمت با AI","ساخت اولین نمونه‌کار","قیمت‌گذاری و بسته خدمات","پیدا کردن مشتری و پروژه","ساخت رزومه و پروفایل","ارائه و مذاکره","پروژه درآمدی","برنامه ۳۰ روزه شروع کار"]}
];

const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
const KEY={saved:"savedCourses",progress:"courseProgress",tickets:"supportTickets",name:"name",theme:"theme",install:"installHintDismissed"};
const get=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}};
const set=(key,value)=>localStorage.setItem(key,JSON.stringify(value));
const fa=n=>Number(n||0).toLocaleString("fa-IR");

function card(c){const p=courseProgress(c.id);return `<article class="course-card glass"><div><span class="course-icon">${c.icon}</span><div><h3>${c.title}</h3><span class="badge">${c.level}</span><p>${c.desc}</p></div></div><div class="course-card-foot"><div class="mini-progress"><i style="width:${p}%"></i></div><span class="progress-label">${fa(p)}٪</span></div><button class="secondary" onclick="showCourse('${c.id}')">مشاهده دوره ←</button></article>`}
function renderCourses(){$("#homeCourses").innerHTML=courses.map(card).join("");$("#allCourses").innerHTML=courses.map(card).join("")}
function courseProgress(id){const p=get(KEY.progress,{});const c=courses.find(x=>x.id===id);if(!c)return 0;return Math.round((c.lessons.filter((_,i)=>p[`${id}:${i}`]).length/c.lessons.length)*100)}
function overallProgress(){const saved=get(KEY.saved,[]);if(!saved.length)return 0;return Math.round(saved.reduce((sum,id)=>sum+courseProgress(id),0)/saved.length)}
function isSaved(id){return get(KEY.saved,[]).includes(id)}
function toggleLesson(id,index){const p=get(KEY.progress,{});const k=`${id}:${index}`;p[k]=!p[k];set(KEY.progress,p);renderProfile();showCourse(id);toast(p[k]?"جلسه به عنوان تکمیل‌شده ثبت شد.":"وضعیت جلسه به حالت ناتمام برگشت.");}
function showCourse(id){
 const c=courses.find(x=>x.id===id); if(!c)return;
 const saved=isSaved(id),p=courseProgress(id),progress=get(KEY.progress,{});
 $("#courseDetail").innerHTML=`<div class="detail-hero glass"><div class="detail-title-row"><span class="course-icon big">${c.icon}</span><div><span class="eyebrow">${c.level}</span><h1>${c.title}</h1></div></div><p>${c.about}</p><div class="detail-meta"><span class="badge">جلسات: ${fa(c.sessions)}</span><span class="badge">${c.duration}</span><span class="badge">مدرس: مهندس امیری</span></div><div class="detail-progress"><div class="row"><strong>پیشرفت دوره</strong><span>${fa(p)}٪</span></div><div class="progress"><i style="width:${p}%"></i></div></div><button class="primary" onclick="enroll('${c.id}')">${saved?"✓ دوره در پروفایل من است":"افزودن به دوره‌های من"}</button></div><div class="detail-section glass"><h2>مهارت‌هایی که کسب می‌کنی</h2><ul class="skill-list">${c.skills.map(x=>`<li>✓ ${x}</li>`).join("")}</ul></div><div class="detail-section glass"><div class="section-head compact"><div><span class="eyebrow">10 SESSIONS</span><h2>برنامه جلسات</h2></div><span class="badge">${fa(c.sessions)} جلسه</span></div>${c.lessons.map((x,i)=>{const done=!!progress[`${id}:${i}`];return `<div class="lesson-row ${done?"done":""}"><button class="lesson-check" onclick="toggleLesson('${id}',${i})" aria-label="تغییر وضعیت جلسه">${done?"✓":"○"}</button><div class="lesson-info"><strong>جلسه ${fa(i+1)} — ${x}</strong><small>${done?"تکمیل شده":"هنوز تکمیل نشده"}</small></div></div>`}).join("")}</div>`;
 navigate("course-detail");
}
function enroll(id){let saved=get(KEY.saved,[]);if(!saved.includes(id)){saved.push(id);set(KEY.saved,saved);toast("دوره به پروفایل شما اضافه شد.")}else toast("این دوره از قبل در پروفایل شماست.");renderCourses();renderProfile();showCourse(id)}
function updateProfile(){renderProfile()}
function renderProfile(){
 const saved=get(KEY.saved,[]),p=overallProgress(),completed=courses.filter(c=>courseProgress(c.id)===100&&saved.includes(c.id)).length;
 $("#savedCount").textContent=fa(saved.length);$("#overallProgress").textContent=`${fa(p)}٪`;$("#certificateCount").textContent=fa(completed);$("#progressPercent").textContent=`${fa(p)}٪`;$("#progressBar").style.width=`${p}%`;
 $("#profileHint").textContent=saved.length?`${fa(saved.length)} دوره در پروفایل شماست. با تکمیل جلسات، درصد پیشرفت افزایش پیدا می‌کند.`:"با انتخاب یک دوره، مسیر یادگیری تو شروع می‌شود.";
 $("#myCourses").innerHTML=saved.length?saved.map(id=>{const c=courses.find(x=>x.id===id);if(!c)return"";const pr=courseProgress(id);return `<button class="my-course glass" onclick="showCourse('${id}')"><span>${c.icon}</span><div><strong>${c.title}</strong><small>${fa(pr)}٪ پیشرفت</small><div class="mini-progress"><i style="width:${pr}%"></i></div></div><b>←</b></button>`}).join(""):"<div class=\"empty-state glass\">هنوز دوره‌ای انتخاب نکرده‌ای. از بخش دوره‌ها یک مسیر را شروع کن.</div>";
}
function navigate(route){$$('.page').forEach(p=>p.classList.remove('active'));const p=$("#"+route);if(p)p.classList.add('active');$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.route===route));window.scrollTo({top:0,behavior:'smooth'});if(route==='profile')renderProfile()}
function toast(msg){const t=$("#toast");t.textContent=msg;t.classList.add('show');clearTimeout(window.tt);window.tt=setTimeout(()=>t.classList.remove('show'),2800)}
function openModal(title,type){$("#modalTitle").textContent=title;$("#modal").dataset.type=type||'message';$("#modalText").value="";$("#modal").classList.add('open');setTimeout(()=>$("#modalText").focus(),50)}
function saveTicket(){const text=$("#modalText").value.trim();if(!text){toast('لطفاً پیام خود را بنویسید.');return}const tickets=get(KEY.tickets,[]);tickets.unshift({id:Date.now(),type:$("#modal").dataset.type==='issue'?"گزارش مشکل":"پشتیبانی",text,createdAt:new Date().toISOString(),status:"ثبت‌شده"});set(KEY.tickets,tickets);$("#modal").classList.remove('open');renderTickets();toast('پیام شما با موفقیت در سوابق پشتیبانی ثبت شد.');}
function renderTickets(){const tickets=get(KEY.tickets,[]);$("#ticketList").innerHTML=tickets.length?tickets.slice(0,5).map(t=>`<div class="ticket glass"><div><span class="badge">${t.type}</span><strong>${t.text}</strong><small>${new Date(t.createdAt).toLocaleDateString('fa-IR')}</small></div><b>ثبت‌شده</b></div>`).join(''):'<div class="empty-state glass">هنوز پیامی ثبت نکرده‌اید.</div>'}
function renderPath(){const data=[["۱","مقدماتی","از صفر با مفاهیم، ابزارها و اصول استفاده از AI آشنا شو.","beginner"],["۲","پیشرفته","مهارت‌های حرفه‌ای‌تر در پرامپت‌نویسی و Workflow بساز.","advanced"],["۳","حرفه‌ای","پروژه واقعی طراحی و با ابزارهای هوش مصنوعی اجرا کن.","pro"],["۴","کسب درآمد با AI","نمونه‌کار بساز و مهارتت را به فرصت درآمدی تبدیل کن.","income"]];$("#timeline").innerHTML=data.map(x=>`<button class="timeline-card glass" onclick="showCourse('${x[3]}')"><div class="timeline-num">${x[0]}</div><div><h3>${x[1]}</h3><p>${x[2]}</p><span class="path-link">مشاهده دوره ←</span></div></button>`).join('')}
function faq(){openModal('سؤالات متداول','faq');$("#modalText").value='ثبت‌نام چگونه انجام می‌شود؟\nبا انتخاب دوره، آن را به پروفایل خود اضافه کنید.\n\nپیشرفت چگونه محاسبه می‌شود؟\nبا تکمیل هر جلسه، درصد پیشرفت دوره و پروفایل به‌روزرسانی می‌شود.\n\nآیا اطلاعات در حساب آنلاین ذخیره می‌شود؟\nدر این نسخه، اطلاعات روی همین دستگاه و در مرورگر ذخیره می‌شود.'}
function applyTheme(){const light=localStorage.getItem(KEY.theme)==='light';document.body.classList.toggle('light',light);$("#themeBtn").textContent=light?'🌙':'☀️'}
function init(){renderCourses();renderPath();renderProfile();renderTickets();applyTheme();const n=localStorage.getItem(KEY.name);if(n)$("#profileName").textContent=n;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();window.deferredInstall=e;$("#installBtn").hidden=false});}

$$('[data-route]').forEach(b=>b.addEventListener('click',()=>navigate(b.dataset.route)));
$("#themeBtn").onclick=()=>{const light=!document.body.classList.contains('light');localStorage.setItem(KEY.theme,light?'light':'dark');applyTheme();toast(light?'حالت روشن فعال شد.':'حالت تیره فعال شد.')};
$("#messageBtn").onclick=()=>openModal('ارسال پیام به پشتیبانی','message');
$("#issueBtn").onclick=()=>openModal('گزارش مشکل','issue');
$("#faqBtn").onclick=faq;
$("#closeModal").onclick=()=>$("#modal").classList.remove('open');
$("#modal").addEventListener('click',e=>{if(e.target.id==='modal')e.currentTarget.classList.remove('open')});
$("#sendModal").onclick=saveTicket;
$("#editName").onclick=()=>{const n=prompt('نام نمایشی خود را وارد کنید:',localStorage.getItem(KEY.name)||'هنرجوی پادشاه AI');if(n&&n.trim()){localStorage.setItem(KEY.name,n.trim());$("#profileName").textContent=n.trim();toast('نام پروفایل به‌روزرسانی شد.')}};
$("#installBtn").onclick=async()=>{if(!window.deferredInstall){toast('اگر اپ نصب نیست، از منوی مرورگر گزینه نصب را انتخاب کن.');return}window.deferredInstall.prompt();await window.deferredInstall.userChoice;window.deferredInstall=null;$("#installBtn").hidden=true};

init();
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}));
